version: 1.0.{build}
image:
  - Visual Studio 2019

build: off

environment:
  global:
    # Avoid long paths on Windows
    STACK_ROOT: "c:\\s"
    STACK_WORK: ".w"
    WORK_DIR: "c:\\m"
  matrix:
  - ARGS: "--resolver lts-14"

init:
  - SET WORK_DIR_NO_PR=%WORK_DIR%\%APPVEYOR_REPO_BRANCH%
  - SET STACK_ROOT_NO_PR=%STACK_ROOT%\%APPVEYOR_REPO_BRANCH%
  - SET WORK_DIR=%WORK_DIR%\%APPVEYOR_PULL_REQUEST_NUMBER%\%APPVEYOR_REPO_BRANCH%\
  - SET STACK_ROOT=%STACK_ROOT%\%APPVEYOR_PULL_REQUEST_NUMBER%\%APPVEYOR_REPO_BRANCH%\

cache:
- "%STACK_ROOT_NO_PR%"
- "%WORK_DIR_NO_PR%\\%STACK_WORK%"
- "%LOCALAPPDATA%\\Programs\\stack"

before_test:
# Avoid long paths not to each MAX_PATH of 260 chars
- xcopy /q /s /e /r /k /i /v /h /y C:\projects\tutorials "%WORK_DIR%"
- cd "%WORK_DIR%"
# Setup cache dirs
# Debug paths
- Echo WORK_DIR = %WORK_DIR%
- dir %WORK_DIR%
- Echo STACK_ROOT = %STACK_ROOT%


# Install stack
- curl -sSkL https://www.stackage.org/stack/windows-x86_64 -o stack.zip
- 7z x stack.zip stack.exe -aoa

# RDP
- iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test_script:
  - cd "%WORK_DIR%"
  - stack %ARGS% --verbosity warn setup --no-reinstall > nul
  - stack %ARGS% test --no-terminal


notifications:
  - provider: Email
    to:
      - alexey@kuleshevi.ch
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
